In [1]:
import numpy as np
import pandas as pd
import string
import warnings
warnings.filterwarnings('ignore')

import requests

In [2]:
url = "https://www.betexplorer.com/soccer/brazil/serie-a-2021/results/"

In [3]:
header = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"  
 }

r = requests.get(url, headers=header)

In [11]:
#Verificar em qual ponto começa a tabela
pd.read_html(r.text,  decimal='.')[0]

                       38. Round 38. Round.1   1    X   2  Unnamed: 5
0         America MG - Sao Paulo         2:0 NaN  NaN NaN  10.12.2021
1      Atletico GO - Flamengo RJ         2:0 NaN  NaN NaN  10.12.2021
2     Bragantino - Internacional         1:0 NaN  NaN NaN  10.12.2021
3        Juventude - Corinthians         1:0 NaN  NaN NaN  10.12.2021
4    Fluminense - Chapecoense-SC         3:0 NaN  NaN NaN  10.12.2021
..                           ...         ...  ..  ...  ..         ...
433  Chapecoense-SC - Bragantino         0:3 NaN  NaN NaN  30.05.2021
434    Corinthians - Atletico GO         0:1 NaN  NaN NaN  30.05.2021
435           Cuiaba - Juventude         2:2 NaN  NaN NaN  30.05.2021
436      Flamengo RJ - Palmeiras         1:0 NaN  NaN NaN  30.05.2021
437       Sao Paulo - Fluminense         0:0 NaN  NaN NaN  30.05.2021

[438 rows x 6 columns]