In [361]:
# Imports
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

# Objetivo_4: Regras de Associação

## Carregar os dados

In [617]:
# Carrega os dados
dados = pd.read_csv("dados/DataCoSupplyChainDataset.csv", encoding = 'latin1')
dados.head(3)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class

In [764]:
f = dados[['Customer Fname', 'Product Name']]
f= pd.get_dummies(f,prefix=['Product Name'], columns = ['Product Name']).set_index('Customer Fname')
f

,Product Name_Adult dog supplies,Product Name_Baby sweater,Product Name_Bag Boy Beverage Holder,Product Name_Bag Boy M330 Push Cart,Product Name_Bowflex SelectTech 1090 Dumbbells,Product Name_Bridgestone e6 Straight Distance NFL Carolina,Product Name_Bridgestone e6 Straight Distance NFL San Dieg,Product Name_Bridgestone e6 Straight Distance NFL Tennesse,Product Name_Brooks Women's Ghost 6 Running Shoe,Product Name_Bushnell Pro X7 Jolt Slope Rangefinder,...,Product Name_Under Armour Women's Ignite Slide,Product Name_Under Armour Women's Micro G Skulpt Running S,Product Name_Web Camera,Product Name_Yakima DoubleDown Ace Hitch Mount 4-Bike Rack,Product Name_adidas Brazuca 2014 Official Match Ball,Product Name_adidas Kids' F5 Messi FG Soccer Cleat,Product Name_adidas Men's F10 Messi TRX FG Soccer Cleat,Product Name_adidas Men's Germany Black Crest Away Tee,Product Name_adidas Youth Germany Black/Red Away Match Soc,Product Name_insta-bed Neverflat Air Mattress
Customer Fname,,,,,,,,,,,,,,,,,,,,,
Cally,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Irene,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gillian,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Orli,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Maria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ronald,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
John,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Andrea,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [766]:
#Regras de associação verificar o suporte acima de 1%
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(f, min_support =  0.00015, use_colnames = True)
frequent_itemsets = frequent_itemsets.sort_values(by=['support'], ascending = False)
frequent_itemsets

     support                                           itemsets
69  0.135803    (Product Name_Perfect Fitness Perfect Rip Deck)
54  0.123234  (Product Name_Nike Men's CJ Elite 2 TD Footbal...
57  0.116525  (Product Name_Nike Men's Dri-FIT Victory Golf ...
65  0.106903    (Product Name_O'Brien Men's Neoprene Life Vest)
22  0.095973  (Product Name_Field & Stream Sportsman 16 Gun ...
..       ...                                                ...
28  0.000194   (Product Name_Garmin Forerunner 910XT GPS Watch)
88  0.000188    (Product Name_Titleist Club Glove Travel Cover)
34  0.000177   (Product Name_GoPro HERO3+ Black Edition Camera)
17  0.000161  (Product Name_Diamondback Boys' Insight 24 Per...
18  0.000155  (Product Name_Diamondback Girls' Clarity 24 Hy...

[113 rows x 2 columns]

In [767]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules.sort_values(by=['lift'], ascending = False).drop(['antecedent support', 'consequent support', 'leverage', 'conviction'], axis=1)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [768]:
df_ar = association_rules(frequent_itemsets, metric = "confidence", min_threshold = 0.6)
df_ar

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []